# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d061d7f34716579faf5ef9d7dfb36d35c7592f2166f3d6cb8390ba3f4cc859d903b2b437bd62ba669863ce4a94e16dd3b2e212b0457c35a5b49270f4a4c0176

test:
  secret_key_base: 4bbaec48f86c66544142735458a95d880955538ad6387ad4147622e687f98c5c6e7a6b2e6c0e2bac3b4124748760be123db37911af5a63c1619d9636e2fddd1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
